### ISSUE TITLE
madcore access grant team

### ISSUE THREAD

**Issue by styk-tv** [madcore-ai/cli#130]
`madcore access grant team`

section in `~/.madcore/config` that will allow me to grant predefined (manually added)

```
access
    user1:
        ip:
            - xx.xx.xx.xx
            - yy.yy.yy.yy
        ssh:
            - ssh-rsa AAAbcdee...
            - ssh-rsa AAAcdefg...
    user2:
        ip:
            - zz.zz.zz.zz
        ssh:
            - ssh-rsa AAAffggtt...
```

once defined in config file can be added as bulk to followme security group in core. this is using local credentials and must be executed against aws from aws credentials on same user account as madcore installation.  first look up cloudformation for followme. identify id of the security group, use boto to add 22,443,8080 for each ip in the ip lists.

then, ssh into core instance and add each public ssh key from ssh lists into default ubuntu user `~/.ssh/authorized_keys` file
